pipeline {
    agent any
    stages {
        stage('Deploy to Kubernetes') {
            steps {
                withKubeCredentials(kubectlCredentials: [[
                    clusterName: 'EKS-1',
                    credentialsId: 'k8s-token',
                    namespace: 'webapps',
                    serverUrl: 'https://E3ABB38582E48A9A6494F670372FEEF4.gr7.ap-south-1.eks.amazonaws.com'
                ]]) {
                    sh "kubectl apply -f deployment-service.yml"
                }
            }
        }
        stage('Verify Deployment') {
            steps {
                withKubeCredentials(kubectlCredentials: [[
                    clusterName: 'EKS-1',
                    credentialsId: 'k8s-token',
                    namespace: 'webapps',
                    serverUrl: 'https://E3ABB38582E48A9A6494F670372FEEF4.gr7.ap-south-1.eks.amazonaws.com'
                ]]) {
                    sh "kubectl get svc -n webapps"
                    sh "kubectl get pods -n webapps"
                }
            }
        }
    }
}
